# Generated by Django 4.2 on 2025-11-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-star', max_length=50)),
                ('color', models.CharField(default='#ffd700', max_length=20)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.IntegerField()),
                ('points_reward', models.IntegerField(default=50)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('founder', 'Group Founder'), ('active_member', 'Active Member'), ('session_creator', 'Session Creator'), ('perfect_attendance', 'Perfect Attendance'), ('social_butterfly', 'Social Butterfly'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('streak_master', 'Streak Master'), ('veteran', 'Veteran'), ('helpful', 'Helpful Member')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=10)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-trophy', max_length=50)),
                ('color', models.CharField(default='#667eea', max_length=20)),
                ('requirement_value', models.IntegerField(default=0)),
                ('requirement_description', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type', 'tier'],
                'unique_together': {('badge_type', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('points_from_badges', models.IntegerField(default=0)),
                ('points_from_sessions', models.IntegerField(default=0)),
                ('points_from_groups', models.IntegerField(default=0)),
                ('points_from_social', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Points',
                'verbose_name_plural': 'User Points',
            },
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_start_date', models.DateField(blank=True, null=True)),
                ('total_sessions_attended', models.IntegerField(default=0)),
                ('total_groups_joined', models.IntegerField(default=0)),
                ('total_sessions_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Streak',
                'verbose_name_plural': 'Study Streaks',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
