# Generated by Django 4.2 on 2025-11-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_sessions', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField(default=0)),
                ('member_growth_rate', models.FloatField(default=0.0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('completed_sessions', models.IntegerField(default=0)),
                ('cancelled_sessions', models.IntegerField(default=0)),
                ('average_attendance_rate', models.FloatField(default=0.0)),
                ('most_active_member_score', models.IntegerField(default=0)),
                ('sessions_this_month', models.IntegerField(default=0)),
                ('sessions_last_month', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='groups.studygroup')),
                ('most_active_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Analytics',
                'verbose_name_plural': 'Group Analytics',
            },
        ),
        migrations.CreateModel(
            name='SessionAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_sessions.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_attended', models.IntegerField(default=0)),
                ('sessions_created', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('activity_score', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_score'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
