# Generated by Django 4.2 on 2025-11-08 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('user_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_session_reminders', models.BooleanField(default=True)),
                ('email_join_requests', models.BooleanField(default=True)),
                ('email_request_responses', models.BooleanField(default=True)),
                ('email_new_members', models.BooleanField(default=False)),
                ('email_session_updates', models.BooleanField(default=True)),
                ('inapp_session_reminders', models.BooleanField(default=True)),
                ('inapp_join_requests', models.BooleanField(default=True)),
                ('inapp_request_responses', models.BooleanField(default=True)),
                ('inapp_new_members', models.BooleanField(default=True)),
                ('inapp_session_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('join_request', 'Join Request'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('new_member', 'New Member'), ('session_created', 'Session Created'), ('session_cancelled', 'Session Cancelled'), ('group_update', 'Group Update'), ('member_left', 'Member Left')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.studygroup')),
                ('join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.joinrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_sessions.studysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
